version: '3.9'

name: fastapi-app

services:
  web_app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: web_app
    volumes:
      - ..:/app/
    env_file:
      - ../.env
    command: "uvicorn --factory app.api.main:start_app --reload --host 0.0.0.0 --port 8000"
